//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaEstates
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.Supplies = new HashSet<Supplies>();
        }
    
        public int Id_demand { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<int> Id_agent { get; set; }
        public Nullable<int> Id_client { get; set; }
        public Nullable<int> Id_type { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Id_demand_flat { get; set; }
        public Nullable<int> Id_demand_house { get; set; }
        public Nullable<int> Id_demand_land { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Client Client { get; set; }
        public virtual DemandOfFlat DemandOfFlat { get; set; }
        public virtual DemandOfHouse DemandOfHouse { get; set; }
        public virtual DemandOfLand DemandOfLand { get; set; }
        public virtual TypeOfEstate TypeOfEstate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplies> Supplies { get; set; }
    }
}
