//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaEstates
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstateObj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstateObj()
        {
            this.Supplies = new HashSet<Supplies>();
        }
    
        public int Id_estate { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Number_home { get; set; }
        public Nullable<int> Number_flat { get; set; }
        public Nullable<int> id_district { get; set; }
        public Nullable<int> Id_type { get; set; }
    
        public virtual District District { get; set; }
        public virtual TypeOfEstate TypeOfEstate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplies> Supplies { get; set; }
    }
}
