//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaEstates
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstateEntities : DbContext
    {
        private static EstateEntities _context;
        public EstateEntities()
            : base("name=EstateEntities")
        {
        }
    
        public static EstateEntities GetContext()
        {
            if(_context == null)
                _context = new EstateEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Demand> Demand { get; set; }
        public virtual DbSet<DemandOfFlat> DemandOfFlat { get; set; }
        public virtual DbSet<DemandOfHouse> DemandOfHouse { get; set; }
        public virtual DbSet<DemandOfLand> DemandOfLand { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<EstateObj> EstateObj { get; set; }
        public virtual DbSet<Supplies> Supplies { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfEstate> TypeOfEstate { get; set; }
    }
}
